version: '3'

services:

  server:
    container_name: REST-api
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 8005:8005
    expose:
      - 8005

  frontend:
    container_name: Frontend-cognitiva
    build: ./frontend
    volumes:
      - .:/user/src/app
    ports:
      - 3000:3000
    expose:
      - 3000






